### ISSUE TITLE
Error with setting root date 

### ISSUE THREAD

**Issue by dylanHco** [tothuhien/lsd2#31]
Hello- 
I am trying to date the root node with -a b(-65,-55) and get an syntax error. Is it possible to give the root node an interval ? 

~/bigdata/lsd2/src/lsd2 -i mytree6.tree -f 100 -s 1748014 -a b(-65,-55) -z 0 -u 0 -l -1 -o ~/bigdata/CH3-150/LCOMP_8_outfiles/LSD_OUT/LSD12

Thanks,
Dylan

**Comment by tothuhien** [comment]
Hi Dylan,

For the root interval, it should be put in quote, so -a 'b(-65,-55)'

Cheers,
Hien

**Comment by dylanHco** [comment]
Hi Hien,

Thanks for the quick response! I tried that convention using the quotes and get another error:

TREE 1
*PROCESSING:
Reading the tree ... 
Collapse 0 (over 82) internal branches having branch length <= -1
 (settable via option -l)
Parameter to adjust variances was set to 0.0047377 (settable via option -b)
Minimum branch length of time scaled tree (settable via option -u and -U): 0
Error: There's conflict or not enough signal in the input temporal constraints.


Code: ~/bigdata/lsd2/src/lsd2 -i DROOT.tree -f 100 -s 1748014 -a 'b(-65,-55)' -z 0 -u 0 -l -1 -v 2  -o ~/bigdata/CH3-150/LCOMP_8_outfiles/LSD_OUT/LSD15

Thanks for any suggestion,
Dylan

**Comment by tothuhien** [comment]
Hi Dylan,

It's because if all of your tips date are equal, you need at least one fixed calibration point in order to have unique optimal solution. So the root date in this case should be a precise value, not an interval. Otherwise, given any root date within that interval, we can always have a corresponding rate which give us the same objective function value. You might probably, if you want, run it twice with respectively upper/lower bound of that interval, and merge the results.

Cheers,
Hien

**Comment by dylanHco** [comment]
Hi Hien,

This makes sense! Thank you for clarifying. 

My best,
Dylan
