### ISSUE TITLE
Confidence interval values

### ISSUE THREAD

**Issue by dylanHco** [tothuhien/lsd2#32]
Hi again Hien,

I have another question about confidence intervals. I have been getting some weird values on some of the nodes. See this tree attached for an example. The root node is supposed to be -65 mya old. The next node up from it is: 2.33388e-310, 2.33388e-310. I am guessing it has to do with the small branch lengths? There are other nodes like it on this tree. Is there a parameter I can use to adjust it so these numbers make sense? 

I have also been trying this in iqtree2 the newest version (covid). I get similar errors in both.

Thanks so much again! 

[LSD14.nexus.pdf](https://github.com/tothuhien/lsd2/files/5252274/LSD14.nexus.pdf)

**Comment by tothuhien** [comment]
Hi Dylan,

It's indeed weird. I'm looking at this and will let you know.

Cheers,
Hien

**Comment by dylanHco** [comment]
Thanks for checking into this too. Looking more closely at some of the dates/trees I have generated, I noticed that if I look at the absolute dates for nodes there are no weird numbers Its only when I want use to confidence intervals I run into some issues. Attached is a the same phylogeny as above, but just using one date per node. 

Best,
Dylan


[LSD14_2ABSDATES.nexus.pdf](https://github.com/tothuhien/lsd2/files/5257206/LSD14_2ABSDATES.nexus.pdf)

**Comment by tothuhien** [comment]
Hi Dylan,

I've just found the bug of this issue. Those weird values are associated with null branches on the output tree, i.e. those of branch length 0. So their dates and CI values should be the same as those of their parents. So for the sake of simplicity, I didn't put CI values of those nodes. In some recent versions, I just decided to put them so that those trees can be read consistently in R; but forgot to assign correct values for them. I've just fixed that in the latest commit. Could you try again? If you don't want null branches in the output tree, jet set option -u to a positive value. Thanks for pointing this out.

Cheers,
Hien

**Comment by dylanHco** [comment]
Hello Hien,

Yes it worked!  I used -u 1 and now all the dates make sense. Thank you so much for your help and making this program easy to use and understand! 

Best,
Dylan

**Comment by tothuhien** [comment]
Thanks for you feedback :)
